[package]
name = "ken-matsui/uuid"
version = "0.1.0"
description = "UUID in WebAssembly"
license = "MIT"
readme = "README.md"
repository = "https://github.com/ken-matsui/uuid-v4-cli"
homepage = "https://github.com/ken-matsui/uuid-v4-cli#readme"

[[module]]
name = "uuid"
source = "target/wasm32-wasi/release/uuid.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.1.0-unstable"

[[command]]
name = "uuid"
module = "uuid"
